name: Build & Deploy to Kubernetes

on:
  push:
    branches: [main]

env:
  NAMESPACE: three-body

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: frontend
            path: frontend
          - name: backend-go
            path: go
          - name: backend-laravel
            path: laravel

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push image to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.path }}
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ matrix.name }}:latest

  deploy-to-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      - name: Apply manifests to Kubernetes
        run: |
          kubectl apply -n ${{ env.NAMESPACE }} -f k8s/

      - name: Wait for deployments to be ready
        run: |
          kubectl rollout status deployment/frontend -n ${{ env.NAMESPACE }}
          kubectl rollout status deployment/backend-go -n ${{ env.NAMESPACE }}
          kubectl rollout status deployment/backend-laravel -n ${{ env.NAMESPACE }}
