# .github/workflows/ci-cd-k8s.yml

name: Build & Deploy to Kubernetes

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: yudasumbowo
  NAMESPACE: three-body

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, go, laravel]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: yudaadisumbowo@gmail.com
          password: dckr_pat_qmWw2l2w-W-RmodqG1n1FVLOhtw

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: yudasumbowo/${{ matrix.service }}:latest

# .github/workflows/ci-cd-k8s.yml

  deploy-to-k8s:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Deploy to Kubernetes
        run: |
          kubectl replace --force -f k8s/ci-cd-k8s.yml -n ${{ env.NAMESPACE }}

